let newBtn = document.createElement("button");
newBtn.innerText = "click me";
console.dir(newBtn);
let div = document.getElementById("box");
console.dir(div);
//div.append(newBtn);
//div.prepend(newBtn);
//div.before(newBtn);
//div.after(newBtn);
let body = document.querySelector("body");
body.prepend(newBtn);
newBtn.style.backgroundColor = "grey";
newBtn.style.color = "white";
newBtn.style.height = "40px";
newBtn.style.widows = "15px";
let h1 = document.createElement("h2");
h1.innerText = "Addation of heading";
let p = document.querySelector("p");
p.before(h1);